version: 2

dependencies:
  pre:
    - wget 
    - chmod +x ./genymotion https://dl.genymotion.com/releases/genymotion-2.11.0/genymotion-2.11.0-linux_x64.bin
    - sudo yes | ./genymotion
  post:
    - sudo /opt/genymobile/gmtool config username $GM_USER password $GM_PASS

test:
  pre:
    - sudo /opt/genymobile/gmtool --cloud admin startdisposable "Custom Phone - 7.1.0 - API 25 - 768x1280" testDevice
  override:
    - ./gradlew connectedAndroidTest --console=plain
