version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-24-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Genymotion
          command: wget https://dl.genymotion.com/releases/genymotion-2.11.0/genymotion-2.11.0-linux_x64.bin
      - run:
          name: Pre-install Genymotion
          command: chmod +x ./genymotion-2.11.0-linux_x64.bin 
      - run:
          name: Install Genymotion
          command: sudo yes | ./genymotion-2.11.0-linux_x64.bin
      - run:
          name: Configure Genymotion
          command: sudo /opt/genymobile/gmtool config username $GM_USER password $GM_PASS
      - run:
          name: Start Genymotion Cloud device
          command: opt/genymobile/gmtool --cloud admin startdisposable "Custom Phone - 7.1.0 - API 25 - 768x1280" testDevice
      - run:
          name: Run the tests
          command: ./gradlew connectedAndroidTest --console=plain
      - store_artifacts:
          path: binocle/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
